-- ads_in_app_event_metrics_by_day_report
-- Batch-based daily snapshot table for TikTok Ads In-App Event Metrics
{% assign target_dataset = vars.target_dataset_id %}
{% assign target_table_id = 'ads_in_app_event_metrics_by_day_report' %}

{% assign source_dataset = vars.source_dataset_id %}
{% assign source_table_id = 'ads_in_app_event_metrics_by_day' %}

-- Declare all variables at the top
DECLARE table_exists BOOL DEFAULT FALSE;
DECLARE min_date DATE;
DECLARE max_date DATE;

-- Check if the source table exists
SET table_exists = (
  SELECT COUNT(*) > 0
  FROM `{{source_dataset}}.INFORMATION_SCHEMA.TABLES`
  WHERE table_name = '{{source_table_id}}'
);

-- Only run the ETL logic if the source table exists
IF table_exists THEN

  -- Create target table if it doesn't exist
  CREATE TABLE IF NOT EXISTS `{{target_dataset}}.{{target_table_id}}` (
    ad_id STRING NOT NULL,
    stat_time_day DATE NOT NULL,
    _gn_id STRING,
    tenant STRING,
    -- Metrics columns (casted to FLOAT64)
    real_time_app_install FLOAT64,
    real_time_app_install_cost FLOAT64,
    app_install FLOAT64,
    cost_per_app_install FLOAT64,
    registration FLOAT64,
    cost_per_registration FLOAT64,
    registration_rate FLOAT64,
    total_registration FLOAT64,
    cost_per_total_registration FLOAT64,
    purchase FLOAT64,
    cost_per_purchase FLOAT64,
    purchase_rate FLOAT64,
    total_purchase FLOAT64,
    cost_per_total_purchase FLOAT64,
    value_per_total_purchase FLOAT64,
    total_purchase_value FLOAT64,
    total_active_pay_roas FLOAT64,
    app_event_add_to_cart FLOAT64,
    cost_per_app_event_add_to_cart FLOAT64,
    app_event_add_to_cart_rate FLOAT64,
    total_app_event_add_to_cart FLOAT64,
    cost_per_total_app_event_add_to_cart FLOAT64,
    value_per_total_app_event_add_to_cart FLOAT64,
    total_app_event_add_to_cart_value FLOAT64,
    checkout FLOAT64,
    cost_per_checkout FLOAT64,
    checkout_rate FLOAT64,
    total_checkout FLOAT64,
    cost_per_total_checkout FLOAT64,
    value_per_checkout FLOAT64,
    total_checkout_value FLOAT64,
    view_content FLOAT64,
    cost_per_view_content FLOAT64,
    view_content_rate FLOAT64,
    total_view_content FLOAT64,
    cost_per_total_view_content FLOAT64,
    value_per_total_view_content FLOAT64,
    total_view_content_value FLOAT64,
    next_day_open FLOAT64,
    cost_per_next_day_open FLOAT64,
    next_day_open_rate FLOAT64,
    total_next_day_open FLOAT64,
    cost_per_total_next_day_open FLOAT64,
    add_payment_info FLOAT64,
    cost_per_add_payment_info FLOAT64,
    add_payment_info_rate FLOAT64,
    total_add_payment_info FLOAT64,
    cost_total_add_payment_info FLOAT64,
    add_to_wishlist FLOAT64,
    cost_per_add_to_wishlist FLOAT64,
    add_to_wishlist_rate FLOAT64,
    total_add_to_wishlist FLOAT64,
    cost_per_total_add_to_wishlist FLOAT64,
    value_per_total_add_to_wishlist FLOAT64,
    total_add_to_wishlist_value FLOAT64,
    launch_app FLOAT64,
    cost_per_launch_app FLOAT64,
    launch_app_rate FLOAT64,
    total_launch_app FLOAT64,
    cost_per_total_launch_app FLOAT64,
    complete_tutorial FLOAT64,
    cost_per_complete_tutorial FLOAT64,
    complete_tutorial_rate FLOAT64,
    total_complete_tutorial FLOAT64,
    cost_per_total_complete_tutorial FLOAT64,
    value_per_total_complete_tutorial FLOAT64,
    total_complete_tutorial_value FLOAT64,
    create_group FLOAT64,
    cost_per_create_group FLOAT64,
    create_group_rate FLOAT64,
    total_create_group FLOAT64,
    cost_per_total_create_group FLOAT64,
    value_per_total_create_group FLOAT64,
    total_create_group_value FLOAT64,
    join_group FLOAT64,
    cost_per_join_group FLOAT64,
    join_group_rate FLOAT64,
    total_join_group FLOAT64,
    cost_per_total_join_group FLOAT64,
    value_per_total_join_group FLOAT64,
    total_join_group_value FLOAT64,
    create_gamerole FLOAT64,
    cost_per_create_gamerole FLOAT64,
    create_gamerole_rate FLOAT64,
    total_create_gamerole FLOAT64,
    cost_per_total_create_gamerole FLOAT64,
    value_per_total_create_gamerole FLOAT64,
    total_create_gamerole_value FLOAT64,
    spend_credits FLOAT64,
    cost_per_spend_credits FLOAT64,
    spend_credits_rate FLOAT64,
    total_spend_credits FLOAT64,
    cost_per_total_spend_credits FLOAT64,
    value_per_total_spend_credits FLOAT64,
    total_spend_credits_value FLOAT64,
    achieve_level FLOAT64,
    cost_per_achieve_level FLOAT64,
    achieve_level_rate FLOAT64,
    total_achieve_level FLOAT64,
    cost_per_total_achieve_level FLOAT64,
    value_per_total_achieve_level FLOAT64,
    total_achieve_level_value FLOAT64,
    unlock_achievement FLOAT64,
    cost_per_unlock_achievement FLOAT64,
    unlock_achievement_rate FLOAT64,
    total_unlock_achievement FLOAT64,
    cost_per_total_unlock_achievement FLOAT64,
    value_per_total_unlock_achievement FLOAT64,
    total_unlock_achievement_value FLOAT64,
    sales_lead FLOAT64,
    cost_per_sales_lead FLOAT64,
    sales_lead_rate FLOAT64,
    total_sales_lead FLOAT64,
    cost_per_total_sales_lead FLOAT64,
    value_per_total_sales_lead FLOAT64,
    total_sales_lead_value FLOAT64,
    in_app_ad_click FLOAT64,
    cost_per_in_app_ad_click FLOAT64,
    in_app_ad_click_rate FLOAT64,
    total_in_app_ad_click FLOAT64,
    cost_per_total_in_app_ad_click FLOAT64,
    value_per_total_in_app_ad_click FLOAT64,
    total_in_app_ad_click_value FLOAT64,
    in_app_ad_impr FLOAT64,
    cost_per_in_app_ad_impr FLOAT64,
    in_app_ad_impr_rate FLOAT64,
    total_in_app_ad_impr FLOAT64,
    cost_per_total_in_app_ad_impr FLOAT64,
    value_per_total_in_app_ad_impr FLOAT64,
    total_in_app_ad_impr_value FLOAT64,
    loan_apply FLOAT64,
    cost_per_loan_apply FLOAT64,
    loan_apply_rate FLOAT64,
    total_loan_apply FLOAT64,
    cost_per_total_loan_apply FLOAT64,
    loan_credit FLOAT64,
    cost_per_loan_credit FLOAT64,
    loan_credit_rate FLOAT64,
    total_loan_credit FLOAT64,
    cost_per_total_loan_credit FLOAT64,
    loan_disbursement FLOAT64,
    cost_per_loan_disbursement FLOAT64,
    loan_disbursement_rate FLOAT64,
    total_loan_disbursement FLOAT64,
    cost_per_total_loan_disbursement FLOAT64,
    login FLOAT64,
    cost_per_login FLOAT64,
    login_rate FLOAT64,
    total_login FLOAT64,
    cost_per_total_login FLOAT64,
    ratings FLOAT64,
    cost_per_ratings FLOAT64,
    ratings_rate FLOAT64,
    total_ratings FLOAT64,
    cost_per_total_ratings FLOAT64,
    value_per_total_ratings FLOAT64,
    total_ratings_value FLOAT64,
    search FLOAT64,
    cost_per_search FLOAT64,
    search_rate FLOAT64,
    total_search FLOAT64,
    cost_per_total_search FLOAT64,
    start_trial FLOAT64,
    cost_per_start_trial FLOAT64,
    start_trial_rate FLOAT64,
    total_start_trial FLOAT64,
    cost_per_total_start_trial FLOAT64,
    subscribe FLOAT64,
    subscribe_rate FLOAT64,
    total_subscribe FLOAT64,
    cost_per_total_subscribe FLOAT64,
    value_per_total_subscribe FLOAT64,
    total_subscribe_value FLOAT64,
    _fivetran_synced TIMESTAMP
  );

  -- Step 1: Create temp table for latest batch
  CREATE TEMP TABLE latest_batch AS
  WITH base AS (
    SELECT * FROM `{{source_dataset}}.{{source_table_id}}`
  ),
  ordered AS (
    SELECT *,
      TIMESTAMP_DIFF(
        _time_extracted,
        LAG(_time_extracted) OVER (ORDER BY _time_extracted),
        SECOND
      ) AS diff_seconds
    FROM base
  ),
  batches AS (
    SELECT *,
      SUM(CASE WHEN diff_seconds IS NULL OR diff_seconds > 120 THEN 1 ELSE 0 END)
        OVER (ORDER BY _time_extracted) AS batch_id
    FROM ordered
  ),
  ranked_batches AS (
    SELECT *,
      RANK() OVER (ORDER BY batch_id DESC) AS batch_rank
    FROM batches
  )
  SELECT *
  FROM ranked_batches
  WHERE batch_rank = 1;

  -- Step 2: Assign min/max dates using SET + scalar subqueries
  SET min_date = (
    SELECT MIN(DATE(stat_time_day)) FROM latest_batch
  );

  SET max_date = (
    SELECT MAX(DATE(stat_time_day)) FROM latest_batch
  );

  -- Step 3: Conditional delete and insert
  BEGIN TRANSACTION;

    IF EXISTS (
      SELECT 1
      FROM `{{target_dataset}}.{{target_table_id}}`
      WHERE stat_time_day BETWEEN min_date AND max_date
        AND ad_id IN (
          SELECT DISTINCT ad_id FROM latest_batch
        )
      LIMIT 1
    ) THEN
      DELETE FROM `{{target_dataset}}.{{target_table_id}}`
      WHERE stat_time_day BETWEEN min_date AND max_date
        AND ad_id IN (
          SELECT DISTINCT ad_id FROM latest_batch
        );
    END IF;

    INSERT INTO `{{target_dataset}}.{{target_table_id}}` (
      ad_id,
      stat_time_day,
      _gn_id,
      tenant,
      real_time_app_install,
      real_time_app_install_cost,
      app_install,
      cost_per_app_install,
      registration,
      cost_per_registration,
      registration_rate,
      total_registration,
      cost_per_total_registration,
      purchase,
      cost_per_purchase,
      purchase_rate,
      total_purchase,
      cost_per_total_purchase,
      value_per_total_purchase,
      total_purchase_value,
      total_active_pay_roas,
      app_event_add_to_cart,
      cost_per_app_event_add_to_cart,
      app_event_add_to_cart_rate,
      total_app_event_add_to_cart,
      cost_per_total_app_event_add_to_cart,
      value_per_total_app_event_add_to_cart,
      total_app_event_add_to_cart_value,
      checkout,
      cost_per_checkout,
      checkout_rate,
      total_checkout,
      cost_per_total_checkout,
      value_per_checkout,
      total_checkout_value,
      view_content,
      cost_per_view_content,
      view_content_rate,
      total_view_content,
      cost_per_total_view_content,
      value_per_total_view_content,
      total_view_content_value,
      next_day_open,
      cost_per_next_day_open,
      next_day_open_rate,
      total_next_day_open,
      cost_per_total_next_day_open,
      add_payment_info,
      cost_per_add_payment_info,
      add_payment_info_rate,
      total_add_payment_info,
      cost_total_add_payment_info,
      add_to_wishlist,
      cost_per_add_to_wishlist,
      add_to_wishlist_rate,
      total_add_to_wishlist,
      cost_per_total_add_to_wishlist,
      value_per_total_add_to_wishlist,
      total_add_to_wishlist_value,
      launch_app,
      cost_per_launch_app,
      launch_app_rate,
      total_launch_app,
      cost_per_total_launch_app,
      complete_tutorial,
      cost_per_complete_tutorial,
      complete_tutorial_rate,
      total_complete_tutorial,
      cost_per_total_complete_tutorial,
      value_per_total_complete_tutorial,
      total_complete_tutorial_value,
      create_group,
      cost_per_create_group,
      create_group_rate,
      total_create_group,
      cost_per_total_create_group,
      value_per_total_create_group,
      total_create_group_value,
      join_group,
      cost_per_join_group,
      join_group_rate,
      total_join_group,
      cost_per_total_join_group,
      value_per_total_join_group,
      total_join_group_value,
      create_gamerole,
      cost_per_create_gamerole,
      create_gamerole_rate,
      total_create_gamerole,
      cost_per_total_create_gamerole,
      value_per_total_create_gamerole,
      total_create_gamerole_value,
      spend_credits,
      cost_per_spend_credits,
      spend_credits_rate,
      total_spend_credits,
      cost_per_total_spend_credits,
      value_per_total_spend_credits,
      total_spend_credits_value,
      achieve_level,
      cost_per_achieve_level,
      achieve_level_rate,
      total_achieve_level,
      cost_per_total_achieve_level,
      value_per_total_achieve_level,
      total_achieve_level_value,
      unlock_achievement,
      cost_per_unlock_achievement,
      unlock_achievement_rate,
      total_unlock_achievement,
      cost_per_total_unlock_achievement,
      value_per_total_unlock_achievement,
      total_unlock_achievement_value,
      sales_lead,
      cost_per_sales_lead,
      sales_lead_rate,
      total_sales_lead,
      cost_per_total_sales_lead,
      value_per_total_sales_lead,
      total_sales_lead_value,
      in_app_ad_click,
      cost_per_in_app_ad_click,
      in_app_ad_click_rate,
      total_in_app_ad_click,
      cost_per_total_in_app_ad_click,
      value_per_total_in_app_ad_click,
      total_in_app_ad_click_value,
      in_app_ad_impr,
      cost_per_in_app_ad_impr,
      in_app_ad_impr_rate,
      total_in_app_ad_impr,
      cost_per_total_in_app_ad_impr,
      value_per_total_in_app_ad_impr,
      total_in_app_ad_impr_value,
      loan_apply,
      cost_per_loan_apply,
      loan_apply_rate,
      total_loan_apply,
      cost_per_total_loan_apply,
      loan_credit,
      cost_per_loan_credit,
      loan_credit_rate,
      total_loan_credit,
      cost_per_total_loan_credit,
      loan_disbursement,
      cost_per_loan_disbursement,
      loan_disbursement_rate,
      total_loan_disbursement,
      cost_per_total_loan_disbursement,
      login,
      cost_per_login,
      login_rate,
      total_login,
      cost_per_total_login,
      ratings,
      cost_per_ratings,
      ratings_rate,
      total_ratings,
      cost_per_total_ratings,
      value_per_total_ratings,
      total_ratings_value,
      search,
      cost_per_search,
      search_rate,
      total_search,
      cost_per_total_search,
      start_trial,
      cost_per_start_trial,
      start_trial_rate,
      total_start_trial,
      cost_per_total_start_trial,
      subscribe,
      subscribe_rate,
      total_subscribe,
      cost_per_total_subscribe,
      value_per_total_subscribe,
      total_subscribe_value,
      _fivetran_synced
    )
    SELECT
      ad_id,
      DATE(stat_time_day) AS stat_time_day,
      TO_HEX(MD5(TO_JSON_STRING([
        SAFE_CAST(ad_id AS STRING),
        CAST(DATE(stat_time_day) AS STRING)
      ]))) AS _gn_id,
      tenant,
      SAFE_CAST(real_time_app_install AS FLOAT64),
      SAFE_CAST(real_time_app_install_cost AS FLOAT64),
      SAFE_CAST(app_install AS FLOAT64),
      SAFE_CAST(cost_per_app_install AS FLOAT64),
      SAFE_CAST(registration AS FLOAT64),
      SAFE_CAST(cost_per_registration AS FLOAT64),
      SAFE_CAST(registration_rate AS FLOAT64),
      SAFE_CAST(total_registration AS FLOAT64),
      SAFE_CAST(cost_per_total_registration AS FLOAT64),
      SAFE_CAST(purchase AS FLOAT64),
      SAFE_CAST(cost_per_purchase AS FLOAT64),
      SAFE_CAST(purchase_rate AS FLOAT64),
      SAFE_CAST(total_purchase AS FLOAT64),
      SAFE_CAST(cost_per_total_purchase AS FLOAT64),
      SAFE_CAST(value_per_total_purchase AS FLOAT64),
      SAFE_CAST(total_purchase_value AS FLOAT64),
      SAFE_CAST(total_active_pay_roas AS FLOAT64),
      SAFE_CAST(app_event_add_to_cart AS FLOAT64),
      SAFE_CAST(cost_per_app_event_add_to_cart AS FLOAT64),
      SAFE_CAST(app_event_add_to_cart_rate AS FLOAT64),
      SAFE_CAST(total_app_event_add_to_cart AS FLOAT64),
      SAFE_CAST(cost_per_total_app_event_add_to_cart AS FLOAT64),
      SAFE_CAST(value_per_total_app_event_add_to_cart AS FLOAT64),
      SAFE_CAST(total_app_event_add_to_cart_value AS FLOAT64),
      SAFE_CAST(checkout AS FLOAT64),
      SAFE_CAST(cost_per_checkout AS FLOAT64),
      SAFE_CAST(checkout_rate AS FLOAT64),
      SAFE_CAST(total_checkout AS FLOAT64),
      SAFE_CAST(cost_per_total_checkout AS FLOAT64),
      SAFE_CAST(value_per_checkout AS FLOAT64),
      SAFE_CAST(total_checkout_value AS FLOAT64),
      SAFE_CAST(view_content AS FLOAT64),
      SAFE_CAST(cost_per_view_content AS FLOAT64),
      SAFE_CAST(view_content_rate AS FLOAT64),
      SAFE_CAST(total_view_content AS FLOAT64),
      SAFE_CAST(cost_per_total_view_content AS FLOAT64),
      SAFE_CAST(value_per_total_view_content AS FLOAT64),
      SAFE_CAST(total_view_content_value AS FLOAT64),
      SAFE_CAST(next_day_open AS FLOAT64),
      SAFE_CAST(cost_per_next_day_open AS FLOAT64),
      SAFE_CAST(next_day_open_rate AS FLOAT64),
      SAFE_CAST(total_next_day_open AS FLOAT64),
      SAFE_CAST(cost_per_total_next_day_open AS FLOAT64),
      SAFE_CAST(add_payment_info AS FLOAT64),
      SAFE_CAST(cost_per_add_payment_info AS FLOAT64),
      SAFE_CAST(add_payment_info_rate AS FLOAT64),
      SAFE_CAST(total_add_payment_info AS FLOAT64),
      SAFE_CAST(cost_total_add_payment_info AS FLOAT64),
      SAFE_CAST(add_to_wishlist AS FLOAT64),
      SAFE_CAST(cost_per_add_to_wishlist AS FLOAT64),
      SAFE_CAST(add_to_wishlist_rate AS FLOAT64),
      SAFE_CAST(total_add_to_wishlist AS FLOAT64),
      SAFE_CAST(cost_per_total_add_to_wishlist AS FLOAT64),
      SAFE_CAST(value_per_total_add_to_wishlist AS FLOAT64),
      SAFE_CAST(total_add_to_wishlist_value AS FLOAT64),
      SAFE_CAST(launch_app AS FLOAT64),
      SAFE_CAST(cost_per_launch_app AS FLOAT64),
      SAFE_CAST(launch_app_rate AS FLOAT64),
      SAFE_CAST(total_launch_app AS FLOAT64),
      SAFE_CAST(cost_per_total_launch_app AS FLOAT64),
      SAFE_CAST(complete_tutorial AS FLOAT64),
      SAFE_CAST(cost_per_complete_tutorial AS FLOAT64),
      SAFE_CAST(complete_tutorial_rate AS FLOAT64),
      SAFE_CAST(total_complete_tutorial AS FLOAT64),
      SAFE_CAST(cost_per_total_complete_tutorial AS FLOAT64),
      SAFE_CAST(value_per_total_complete_tutorial AS FLOAT64),
      SAFE_CAST(total_complete_tutorial_value AS FLOAT64),
      SAFE_CAST(create_group AS FLOAT64),
      SAFE_CAST(cost_per_create_group AS FLOAT64),
      SAFE_CAST(create_group_rate AS FLOAT64),
      SAFE_CAST(total_create_group AS FLOAT64),
      SAFE_CAST(cost_per_total_create_group AS FLOAT64),
      SAFE_CAST(value_per_total_create_group AS FLOAT64),
      SAFE_CAST(total_create_group_value AS FLOAT64),
      SAFE_CAST(join_group AS FLOAT64),
      SAFE_CAST(cost_per_join_group AS FLOAT64),
      SAFE_CAST(join_group_rate AS FLOAT64),
      SAFE_CAST(total_join_group AS FLOAT64),
      SAFE_CAST(cost_per_total_join_group AS FLOAT64),
      SAFE_CAST(value_per_total_join_group AS FLOAT64),
      SAFE_CAST(total_join_group_value AS FLOAT64),
      SAFE_CAST(create_gamerole AS FLOAT64),
      SAFE_CAST(cost_per_create_gamerole AS FLOAT64),
      SAFE_CAST(create_gamerole_rate AS FLOAT64),
      SAFE_CAST(total_create_gamerole AS FLOAT64),
      SAFE_CAST(cost_per_total_create_gamerole AS FLOAT64),
      SAFE_CAST(value_per_total_create_gamerole AS FLOAT64),
      SAFE_CAST(total_create_gamerole_value AS FLOAT64),
      SAFE_CAST(spend_credits AS FLOAT64),
      SAFE_CAST(cost_per_spend_credits AS FLOAT64),
      SAFE_CAST(spend_credits_rate AS FLOAT64),
      SAFE_CAST(total_spend_credits AS FLOAT64),
      SAFE_CAST(cost_per_total_spend_credits AS FLOAT64),
      SAFE_CAST(value_per_total_spend_credits AS FLOAT64),
      SAFE_CAST(total_spend_credits_value AS FLOAT64),
      SAFE_CAST(achieve_level AS FLOAT64),
      SAFE_CAST(cost_per_achieve_level AS FLOAT64),
      SAFE_CAST(achieve_level_rate AS FLOAT64),
      SAFE_CAST(total_achieve_level AS FLOAT64),
      SAFE_CAST(cost_per_total_achieve_level AS FLOAT64),
      SAFE_CAST(value_per_total_achieve_level AS FLOAT64),
      SAFE_CAST(total_achieve_level_value AS FLOAT64),
      SAFE_CAST(unlock_achievement AS FLOAT64),
      SAFE_CAST(cost_per_unlock_achievement AS FLOAT64),
      SAFE_CAST(unlock_achievement_rate AS FLOAT64),
      SAFE_CAST(total_unlock_achievement AS FLOAT64),
      SAFE_CAST(cost_per_total_unlock_achievement AS FLOAT64),
      SAFE_CAST(value_per_total_unlock_achievement AS FLOAT64),
      SAFE_CAST(total_unlock_achievement_value AS FLOAT64),
      SAFE_CAST(sales_lead AS FLOAT64),
      SAFE_CAST(cost_per_sales_lead AS FLOAT64),
      SAFE_CAST(sales_lead_rate AS FLOAT64),
      SAFE_CAST(total_sales_lead AS FLOAT64),
      SAFE_CAST(cost_per_total_sales_lead AS FLOAT64),
      SAFE_CAST(value_per_total_sales_lead AS FLOAT64),
      SAFE_CAST(total_sales_lead_value AS FLOAT64),
      SAFE_CAST(in_app_ad_click AS FLOAT64),
      SAFE_CAST(cost_per_in_app_ad_click AS FLOAT64),
      SAFE_CAST(in_app_ad_click_rate AS FLOAT64),
      SAFE_CAST(total_in_app_ad_click AS FLOAT64),
      SAFE_CAST(cost_per_total_in_app_ad_click AS FLOAT64),
      SAFE_CAST(value_per_total_in_app_ad_click AS FLOAT64),
      SAFE_CAST(total_in_app_ad_click_value AS FLOAT64),
      SAFE_CAST(in_app_ad_impr AS FLOAT64),
      SAFE_CAST(cost_per_in_app_ad_impr AS FLOAT64),
      SAFE_CAST(in_app_ad_impr_rate AS FLOAT64),
      SAFE_CAST(total_in_app_ad_impr AS FLOAT64),
      SAFE_CAST(cost_per_total_in_app_ad_impr AS FLOAT64),
      SAFE_CAST(value_per_total_in_app_ad_impr AS FLOAT64),
      SAFE_CAST(total_in_app_ad_impr_value AS FLOAT64),
      SAFE_CAST(loan_apply AS FLOAT64),
      SAFE_CAST(cost_per_loan_apply AS FLOAT64),
      SAFE_CAST(loan_apply_rate AS FLOAT64),
      SAFE_CAST(total_loan_apply AS FLOAT64),
      SAFE_CAST(cost_per_total_loan_apply AS FLOAT64),
      SAFE_CAST(loan_credit AS FLOAT64),
      SAFE_CAST(cost_per_loan_credit AS FLOAT64),
      SAFE_CAST(loan_credit_rate AS FLOAT64),
      SAFE_CAST(total_loan_credit AS FLOAT64),
      SAFE_CAST(cost_per_total_loan_credit AS FLOAT64),
      SAFE_CAST(loan_disbursement AS FLOAT64),
      SAFE_CAST(cost_per_loan_disbursement AS FLOAT64),
      SAFE_CAST(loan_disbursement_rate AS FLOAT64),
      SAFE_CAST(total_loan_disbursement AS FLOAT64),
      SAFE_CAST(cost_per_total_loan_disbursement AS FLOAT64),
      SAFE_CAST(login AS FLOAT64),
      SAFE_CAST(cost_per_login AS FLOAT64),
      SAFE_CAST(login_rate AS FLOAT64),
      SAFE_CAST(total_login AS FLOAT64),
      SAFE_CAST(cost_per_total_login AS FLOAT64),
      SAFE_CAST(ratings AS FLOAT64),
      SAFE_CAST(cost_per_ratings AS FLOAT64),
      SAFE_CAST(ratings_rate AS FLOAT64),
      SAFE_CAST(total_ratings AS FLOAT64),
      SAFE_CAST(cost_per_total_ratings AS FLOAT64),
      SAFE_CAST(value_per_total_ratings AS FLOAT64),
      SAFE_CAST(total_ratings_value AS FLOAT64),
      SAFE_CAST(search AS FLOAT64),
      SAFE_CAST(cost_per_search AS FLOAT64),
      SAFE_CAST(search_rate AS FLOAT64),
      SAFE_CAST(total_search AS FLOAT64),
      SAFE_CAST(cost_per_total_search AS FLOAT64),
      SAFE_CAST(start_trial AS FLOAT64),
      SAFE_CAST(cost_per_start_trial AS FLOAT64),
      SAFE_CAST(start_trial_rate AS FLOAT64),
      SAFE_CAST(total_start_trial AS FLOAT64),
      SAFE_CAST(cost_per_total_start_trial AS FLOAT64),
      SAFE_CAST(subscribe AS FLOAT64),
      SAFE_CAST(subscribe_rate AS FLOAT64),
      SAFE_CAST(total_subscribe AS FLOAT64),
      SAFE_CAST(cost_per_total_subscribe AS FLOAT64),
      SAFE_CAST(value_per_total_subscribe AS FLOAT64),
      SAFE_CAST(total_subscribe_value AS FLOAT64),
      CURRENT_TIMESTAMP() AS _fivetran_synced
    FROM latest_batch;

  COMMIT TRANSACTION;

END IF; 