CREATE TABLE `ad_groups`
(
  adgroup_id STRING NOT NULL,
  creative_material_mode STRING,
  budget_mode STRING,
  scheduled_budget FLOAT64,
  placement_type STRING,
  languages STRING,
  deep_bid_type STRING,
  skip_learning_phase BOOL,
  gender STRING,
  pixel_id STRING,
  frequency_schedule INT64,
  frequency INT64,
  ios14_quota_type STRING,
  bid_type STRING,
  advertiser_id STRING,
  dayparting STRING,
  pacing STRING,
  is_hfss BOOL,
  campaign_name STRING,
  campaign_id STRING,
  adgroup_name STRING,
  billing_event STRING,
  budget FLOAT64,
  is_new_structure BOOL,
  schedule_type STRING,
  modify_time TIMESTAMP,
  schedule_end_time TIMESTAMP,
  create_time TIMESTAMP,
  schedule_start_time TIMESTAMP,
  tenant STRING,
  _time_extracted TIMESTAMP,
  _time_loaded TIMESTAMP
);