CREATE TABLE `ads`
(
  ad_id STRING NOT NULL,
  ad_format STRING,
  campaign_name STRING,
  identity_type STRING,
  campaign_id STRING,
  brand_safety_postbid_partner STRING,
  ad_name STRING,
  avatar_icon_web_uri STRING,
  adgroup_id STRING,
  image_ids STRING,
  call_to_action_id STRING,
  video_id STRING,
  adgroup_name STRING,
  advertiser_id STRING,
  creative_type STRING,
  landing_page_url STRING,
  call_to_action STRING,
  identity_id STRING,
  page_id FLOAT64,
  display_name STRING,
  playable_url STRING,
  is_new_structure BOOL,
  click_tracking_url STRING,
  ad_text STRING,
  is_aco BOOL,
  app_name STRING,
  fallback_type STRING,
  modify_time TIMESTAMP,
  create_time TIMESTAMP,
  tenant STRING,
  _time_extracted TIMESTAMP,
  _time_loaded TIMESTAMP
);