CREATE TABLE `ads_basic_data_metrics_by_day`
(
  ad_id STRING NOT NULL,
  spend STRING,
  cpc STRING,
  cpm STRING,
  impressions STRING,
  clicks STRING,
  ctr STRING,
  reach STRING,
  cost_per_1000_reached STRING,
  conversion STRING,
  cost_per_conversion STRING,
  conversion_rate STRING,
  real_time_conversion STRING,
  real_time_cost_per_conversion STRING,
  real_time_conversion_rate STRING,
  result STRING,
  cost_per_result STRING,
  result_rate STRING,
  real_time_result STRING,
  real_time_cost_per_result STRING,
  real_time_result_rate STRING,
  secondary_goal_result STRING,
  cost_per_secondary_goal_result STRING,
  secondary_goal_result_rate STRING,
  frequency STRING,
  stat_time_day TIMESTAMP NOT NULL,
  tenant STRING,
  _time_extracted TIMESTAMP,
  _time_loaded TIMESTAMP
);